# Generated by Django 5.0.3 on 2024-07-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
